config/routes.rb
Rails.application.routes.draw do

root 'colts#index'
resources :colts





end

app/models/colt.rb
class Colt < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colts_controller.rb
class ColtsController < ApplicationController
  before_action :set_colt, only:[:show,:edit,:update,:destroy]
  def index
    @colts = Colt.all
  end

  def show
  end

  def new
    @colt = Colt.new
  end

  def create
    @colt = Colt.new(colt_params)
    if @colt.save
      flash[:notice] = "A new Colt has been added!"
      redirect_to @colt
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @colt.update(colt_params)
      flash[:notice] = "You updated a Colt!"
      redirect_to @colt
    else
      render :edit
    end
  end

  def destroy
    @colt.destroy
    redirect_to colts_path
  end

  private

  def colt_params
    params.require(:colt).permit(:name, :number, :position)
  end

  def set_colt
    @colt = Colt.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colts/_form.haml
= form_for @colt do |f|
  = f.label :name
  = f.text_field :name
  .div
  = f.label :position
  = f.text_field :position
  .div
  = f.label :number
  = f.number_field :number
  .div
  = f.submit

app/views/colts/edit.haml
= render 'form'
= link_to 'Home', colts_path

app/views/colts/index.haml
-@colts.each do |colt|
  %p= link_to colt.name, colt_path(colt)
  %p= colt.position
  %p= colt.number
  = link_to 'Edit', edit_colt_path(colt)
  = link_to 'Delete', colt_path(colt), method: :delete, data:{confirm: "Delete this Player?"}
  %hr
= link_to 'New Colt', new_colt_path

app/views/colts/new.haml
= render 'form'
= link_to 'Home', colts_path

app/views/colts/show.haml
%p= "Name: #{@colt.name}"
%p= "Position: #{@colt.position}"
%p= "Number: #{@colt.number}"
= link_to 'Roster', colts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ColtsApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:notice]
      = flash[:notice]
    = yield